### ISSUE TITLE
(Projeto) Criar estrutura para conversão dos roteiros em PDF

### ISSUE THREAD

**Issue by dunossauro** [z4r4tu5tr4/python-funcional#25]
1. Adicionar hierarquia em tópicos e sub tópicos para gerar pdfs
2. Alterar roteiros de maneira em que possam ser lidos de maneira corrida
3. criar um index para roteiros, tanto para exibir no readme quanto para usar como início do pdf

**Comment by vmesel** [comment]
@z4r4tu5tr4 faça em latex, assim você conseguirá transferir para PDFs!

**Comment by dunossauro** [comment]
Markdown também converte para pdf

**Comment by vmesel** [comment]
Qualquer coisa, se não tiver jeito (que obviamente tem), Markdown -> HTML -> PDF

**Comment by dunossauro** [comment]
Tem sim cara, eu estou usando.

**Comment by dunossauro** [comment]
Como comentado em #42, os pdfs podem ser gerados pelo typora, porém fazer de maneira automatizada não vai funcionar. Pois as quebras de texto devem ser analizadas manualmente.
