### ISSUE TITLE
(Correção) Roteiro -  4_funcoes_reducao_mapeamento

### ISSUE THREAD

**Issue by Lucasfeelix** [z4r4tu5tr4/python-funcional#26]
Na introdução é mencionado que será falado sobre a função de redução `sum()`, porém, não foi dito nada sobre o mesmo.

**Comment by dunossauro** [comment]
corrigido com o commit 0131b95b4d7e2aceab3b93b816054c8155b6dc4f.
A issue vai voltar para correção.

@Lucasfeelix, você poderia fazer?

**Comment by dunossauro** [comment]
A correção pode ser apontada na issue #17
