### ISSUE TITLE
(Correção) Roteiro 8

### ISSUE THREAD

**Issue by n1lux** [z4r4tu5tr4/python-funcional#37]
Reformular docstring para evitar dupla interpretação.
"""
        A função interna recebe um valor e retorna a soma dos dois valores.

        val_1 está no contexto da função interna, mas val 2 não está no
            contexto da função externa
        """

Ex: var_1 está acessível tanto no contexto da função interna quanto da externa, porém val_2 está acessível somente no contexto da função interna.

**Comment by dunossauro** [comment]
@n1lux, adicionei no board da correções. Você também pode corrigir e mandar o merge caso se sinta a vontade.

**Comment by dunossauro** [comment]
Link do board: https://github.com/z4r4tu5tr4/python-funcional/projects/3

**Comment by dunossauro** [comment]
Confundi o roteiro com a issue. SUAHUSAHSA

Mas resolvido exatamente como disse.

https://github.com/dunossauro/python-funcional/commit/e230fbcfe594180289ad90e45913fca5ba82cdfa
